Repository drujensen/fib, pull requests merged in 2018-10, with the labels that each got.

#78 Add Erlang/Escript
  README.md
  fib.erl
  fib.es
Labels: wip

#70 Add K version
  README.md
  fib.k
  optimized/fib-mem.k
Labels: optimized

#83 Add both memoization and function call optimization to Perl5
  fib-inline.pl
  fib-mem.pl
Labels: optimized

#84 Faster fib-mem.go
  optimized/fib-mem.go
Labels: optimized

#79 Add Erlang-Escript with memoization
  optimized/fib_mem.erl
  optimized/fib_mem.es
Labels: optimized

#67 Tail recursive Fibonacci implementation in OCaml
  fib_tailrec.ml
Labels: optimized

#65 Added fib memoize version Rust and Perl
  fib_mem.pl
  fib_mem.rs
Labels: optimized

#58 Simple memoized Haskell fib
  fib_mem.hs
  fib_tail.hs
Labels: optimized

#56 Add fib_const.nim
  fib_const.nim
Labels: optimized

#54 Add fib-mem.swift
  fib-mem.swift
Labels: optimized

#50 Add Perl 6 version that is memoized
  fib-mem.p6
Labels: optimized

#40 DLang speedup using memoization
  README.md
  fib-mem.d
Labels: optimized

#33 Add iterative Elixir example
  Fib.exs
  optimized/fib-iterative.exs
  optimized/run.sh
Labels: optimized, wip

#73 Added java optimized fibo
  FibOptimized.java
Labels: optimized, wip
